In [8]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('../../data/raw/IMDB_Dataset.csv')

In [10]:
df.sample(10,random_state=42)

                                                  review sentiment
33553  I really liked this Summerslam due to the look...  positive
9427   Not many television shows appeal to quite as m...  positive
199    The film quickly gets to a major chase scene w...  negative
12447  Jane Austen would definitely approve of this o...  positive
39489  Expectations were somewhat high for me when I ...  negative
42724  I've watched this movie on a fairly regular ba...  positive
10822  For once a story of hope highlighted over the ...  positive
49498  Okay, I didn't get the Purgatory thing the fir...  positive
4144   I was very disappointed with this series. It h...  negative
36958  The first 30 minutes of Tinseltown had my fing...  negative

In [11]:
df.columns

Index(['review', 'sentiment'], dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  str
 1   sentiment  50000 non-null  str
dtypes: str(2)
memory usage: 63.6 MB

In [13]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [14]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [15]:
df["sentiment"].unique()

<ArrowStringArray>
['positive', 'negative']
Length: 2, dtype: str

In [16]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [17]:
df["unique_word_count"] = df["review"].apply(
    lambda text: len(
        set(str(text).lower().split())
    )
)

In [19]:
df["word_count"] = df["review"].apply(
    lambda text: len(str(text).split())
)

In [20]:
df["character_count"] = df["review"].apply(
    lambda text: len(str(text))
)

In [21]:
df[
    [
        "review",
        "word_count",
        "character_count",
        "unique_word_count"
    ]
].head()

,review,word_count,character_count,unique_word_count
0,One of the other reviewers has mentioned that ...,307,1761,200
1,A wonderful little production. <br /><br />The...,162,998,112
2,I thought this was a wonderful way to spend ti...,166,926,120
3,Basically there's a family where a little boy ...,138,748,93
4,"Petter Mattei's ""Love in the Time of Money"" is...",230,1317,148

In [22]:
df[
    [
        "word_count",
        "character_count",
        "unique_word_count"
    ]
].describe()

         word_count  character_count  unique_word_count
count  50000.000000     50000.000000       50000.000000
mean     231.156940      1309.431020         148.049780
std      171.343997       989.728014          88.837364
min        4.000000        32.000000           4.000000
25%      126.000000       699.000000          91.000000
50%      173.000000       970.000000         120.000000
75%      280.000000      1590.250000         180.000000
max     2470.000000     13704.000000        1092.000000