In [35]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import (
    CountVectorizer,
    TfidfVectorizer
)

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

import matplotlib.pyplot as plt

In [38]:
df = pd.read_csv( "../../data/processed/processed_reviews.csv")

In [45]:
X_text = df["clean_text"]
y = df["sentiment"]

X_text = df["clean_text"]
y = df["sentiment"]

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


bow_vectorizer = CountVectorizer()

X_train_bow = bow_vectorizer.fit_transform(X_train_text)
X_test_bow = bow_vectorizer.transform(X_test_text)

In [47]:
bow_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

bow_model.fit(X_train_bow,y_train)

y_pred_bow = bow_model.predict(X_test_bow)

In [49]:
bow_accuracy = accuracy_score(
    y_test,
    y_pred_bow
)

bow_precision = precision_score(
    y_test,
    y_pred_bow,
    pos_label="positive"
)

bow_recall = recall_score(
    y_test,
    y_pred_bow,
    pos_label="positive"
)

bow_f1 = f1_score(
    y_test,
    y_pred_bow,
    pos_label="positive"
)

print("BoW Unigram")
print("=" * 30)

print("Accuracy :", bow_accuracy)
print("Precision:", bow_precision)
print("Recall   :", bow_recall)
print("F1 Score :", bow_f1)

BoW Unigram
==============================
Accuracy : 0.8826
Precision: 0.879563492063492
Recall   : 0.8866
F1 Score : 0.8830677290836654

In [50]:
print(
    classification_report(
        y_test,
        y_pred_bow
    )
)

              precision    recall  f1-score   support

    negative       0.89      0.88      0.88      5000
    positive       0.88      0.89      0.88      5000

    accuracy                           0.88     10000
   macro avg       0.88      0.88      0.88     10000
weighted avg       0.88      0.88      0.88     10000

In [56]:
tfidf_vectorizer = TfidfVectorizer()

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_text)

X_test_tfidf = tfidf_vectorizer.transform(X_test_text)


tfidf_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

tfidf_model.fit(X_train_tfidf,y_train)

y_pred_tfidf = tfidf_model.predict(X_test_tfidf)


tfidf_accuracy = accuracy_score(
    y_test,
    y_pred_tfidf
)

tfidf_precision = precision_score(
    y_test,
    y_pred_tfidf,
    pos_label="positive"
)

tfidf_recall = recall_score(
    y_test,
    y_pred_tfidf,
    pos_label="positive"
)

tfidf_f1 = f1_score(
    y_test,
    y_pred_tfidf,
    pos_label="positive"
)

print("TF-IDF Unigram")
print("=" * 30)

print("Accuracy :", tfidf_accuracy)
print("Precision:", tfidf_precision)
print("Recall   :", tfidf_recall)
print("F1 Score :", tfidf_f1)

TF-IDF Unigram
==============================
Accuracy : 0.8926
Precision: 0.883998435054773
Recall   : 0.9038
F1 Score : 0.8937895569620253

In [ ]:
tfidf_ngram_vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    max_features=20000
)

X_train_tfidf_ngram = (tfidf_ngram_vectorizer.fit_transform(X_train_text))
X_test_tfidf_ngram = (tfidf_ngram_vectorizer.transform(X_test_text))

In [59]:
print("Training:",X_train_tfidf_ngram.shape)

print("Testing:",X_test_tfidf_ngram.shape)

tfidf_ngram_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

tfidf_ngram_model.fit(X_train_tfidf_ngram,y_train)

tfidf_ngram_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

tfidf_ngram_model.fit(X_train_tfidf_ngram,y_train)

y_pred_tfidf_ngram = (
    tfidf_ngram_model.predict(
        X_test_tfidf_ngram
    )
)

ngram_accuracy = accuracy_score(
    y_test,
    y_pred_tfidf_ngram
)

ngram_precision = precision_score(
    y_test,
    y_pred_tfidf_ngram,
    pos_label="positive"
)

ngram_recall = recall_score(
    y_test,
    y_pred_tfidf_ngram,
    pos_label="positive"
)

ngram_f1 = f1_score(
    y_test,
    y_pred_tfidf_ngram,
    pos_label="positive"
)

print("TF-IDF Unigram + Bigram")
print("=" * 35)

print("Accuracy :", ngram_accuracy)
print("Precision:", ngram_precision)
print("Recall   :", ngram_recall)
print("F1 Score :", ngram_f1)

Training: (40000, 20000)
Testing: (10000, 20000)
TF-IDF Unigram + Bigram
===================================
Accuracy : 0.8993
Precision: 0.89047525914336
Recall   : 0.9106
F1 Score : 0.900425195293187

In [60]:
results = pd.DataFrame({
    "Representation": [
        "BoW Unigram",
        "TF-IDF Unigram",
        "TF-IDF Unigram + Bigram"
    ],
    "Features": [
        X_train_bow.shape[1],
        X_train_tfidf.shape[1],
        X_train_tfidf_ngram.shape[1]
    ],
    "Accuracy": [
        bow_accuracy,
        tfidf_accuracy,
        ngram_accuracy
    ],
    "Precision": [
        bow_precision,
        tfidf_precision,
        ngram_precision
    ],
    "Recall": [
        bow_recall,
        tfidf_recall,
        ngram_recall
    ],
    "F1 Score": [
        bow_f1,
        tfidf_f1,
        ngram_f1
    ]
})

results

            Representation  Features  Accuracy  Precision  Recall  F1 Score
0              BoW Unigram     80945    0.8826   0.879563  0.8866  0.883068
1           TF-IDF Unigram     80945    0.8926   0.883998  0.9038  0.893790
2  TF-IDF Unigram + Bigram     20000    0.8993   0.890475  0.9106  0.900425

In [61]:
error_analysis = pd.DataFrame({
    "review": X_test_text.values,
    "actual": y_test.values,
    "predicted": y_pred_tfidf_ngram
})

errors = error_analysis[
    error_analysis["actual"] !=
    error_analysis["predicted"]
]

errors.head(20)

                                                review    actual predicted
0    yes mtv really way market daria started clever...  negative  positive
1    story bride fair amusing engaging one filmmake...  negative  positive
14   little quentin seems mastered art cake eating ...  negative  positive
18   film listed made not film available something ...  negative  positive
26   farrah fawcett give award nominated performanc...  positive  negative
28   movie gung ho story carlson makin island raide...  negative  positive
35   known brad linaweaver florida state u early in...  negative  positive
42   order enjoy fur imaginary portrait diane arbus...  negative  positive
45   quite fan michael chabon novel wonder boy beca...  negative  positive
53   tenshu imprisoned sentenced death survives ele...  positive  negative
60   ca believe comment show show genius sure follo...  positive  negative
63   seen branaghs hamlet branagh old speaks freque...  positive  negative
91   lady gentleman really got winner actually boy ...  positive  negative
94   appeared extra location journalist covering da...  negative  positive
96   citizen kane godfather part ii martin dolemite...  positive  negative
115  not movie everyone movie top lover black comed...  positive  negative
123  let start saying love japanese cinema literatu...  negative  positive
130  opinion movie entire video portion movie absol...  negative  positive
141  one people find according jim great television...  negative  positive
155  froggie upset never big party like kid spanky ...  negative  positive

In [62]:
feature_names = (
    tfidf_ngram_vectorizer
    .get_feature_names_out()
)

coefficients = (
    tfidf_ngram_model.coef_[0]
)

In [63]:
coefficient_df = pd.DataFrame({
    "feature": feature_names,
    "coefficient": coefficients
})

In [64]:
print(
    classification_report(
        y_test,
        y_pred_tfidf_ngram,
        target_names=[
            "negative",
            "positive"
        ]
    )
)

              precision    recall  f1-score   support

    negative       0.91      0.89      0.90      5000
    positive       0.89      0.91      0.90      5000

    accuracy                           0.90     10000
   macro avg       0.90      0.90      0.90     10000
weighted avg       0.90      0.90      0.90     10000

In [65]:
import os

os.makedirs(
    "../artifacts",
    exist_ok=True
)

results.to_csv(
    "../artifacts/model_comparison.csv",
    index=False
)

In [66]:
import joblib

joblib.dump(
    tfidf_ngram_vectorizer,
    "../artifacts/tfidf_vectorizer.pkl"
)

['../artifacts/tfidf_vectorizer.pkl']

In [67]:
joblib.dump(
    tfidf_ngram_model,
    "../artifacts/sentiment_model.pkl"
)

['../artifacts/sentiment_model.pkl']

In [68]:
print(
    os.path.exists(
        "../artifacts/tfidf_vectorizer.pkl"
    )
)

print(
    os.path.exists(
        "../artifacts/sentiment_model.pkl"
    )
)

True
True

In [69]:
def predict_sentiment(text):

    cleaned_text = preprocess_text(text)

    vectorized_text = (
        tfidf_ngram_vectorizer.transform(
            [cleaned_text]
        )
    )

    prediction = (
        tfidf_ngram_model.predict(
            vectorized_text
        )[0]
    )

    probability = (
        tfidf_ngram_model.predict_proba(
            vectorized_text
        )[0]
    )

    return prediction, probability